name: Run Airtable Sync

on:
  schedule:
    - cron: "0 6-14 * * 1-5" # Local time (UTC+3) 9-17 hours weekdays
    - cron: "0 21 * * 1-5" # Midnight local time (UTC+3)
  workflow_dispatch: # Enables manual trigger
  push:
    branches:
      - feature/* # Run only on feature branches

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: .
        run: |
          pwd
          python -m pip install --upgrade pip
          pip install -r airtable_sync/requirements.txt

      - name: Run Airtable Sync
        working-directory: .
        env:
          GITHUB_TOKEN: ${{ secrets.AIRSYNC_GITHUB_TOKEN }}
          AIRTABLE_TOKEN: ${{ secrets.AIRSYNC_AIRTABLE_TOKEN }}
        run: |
          python --version
          pwd
          python -m airtable_sync -v
