name: Sync from latest source branch
# Syncs triggered on source changes, i.e. pushes and pull requests when a branch is updated or before merged
on:
  workflow_dispatch: # Enables manual trigger
  push:
    branches-ignore:
      - main # Run on all pushes except for the main branch

  pull_request:
    branches:
      - main # Run on PRs that target the main branch

jobs:
  branch-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy config file
        run: |
          # todo - use a different config file to sync from issues from this repo to an Airtable sandbox base
          cp .github/workflows/branch-config.json $GITHUB_WORKSPACE/config.json

      - name: Run sync
        id: run-airtable-sync
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_PAT }}
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_SYNC_SANDBOX_PAT }}
        run: |
          mv config.json src/config.json
          cd src

          python --version
          which python

          ls -lh
          cat ./config.json

          pwd
          python -m airtable_sync -v
