name: flake8 lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Lint production code
        run: |
          flake8 src --max-line-length=100 --ignore=E501,W503

      - name: Lint test code
        run: |
          flake8 test --max-line-length=100 --ignore=E501,W503

      - name: Lint workflow code
        run: |
          flake8 .github/workflows --max-line-length=100 --ignore=E501,W503
