
name: production sync run history
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Enables manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tqdm requests
          cp .github/workflows/workflow_run_history.py .

      - name: Run workflow_run_history.py
        env:
          GITHUB_AIRTABLE_SYNC_READONLY_ACTION_TOKEN: ${{ secrets.AIRTABLE_SYNC_READONLY_ACTION_TOKEN }}
          GITHUB_AIRTABLE_SYNC_GIST_TOKEN: ${{ secrets.AIRSYNC_GIST_TOKEN }}
        run: |
          owner="${{ github.repository_owner }}"
          repo="${{ github.event.repository.name }}"
          workflow_id=122549153
          echo "Repo Owner: $owner"
          echo "Repo Name: $repo"
          python workflow_run_history.py --owner $owner --repo $repo --id $workflow_id