name: Update sync status

on:
  repository_dispatch:
    types: [sync_status_update]

jobs:
  process-status:
    runs-on: ubuntu-latest
    env:
      STATUS_COMMIT_MESSAGE: "[GitHub Actions Bot] Sync status update"  # Automatic status update commit message

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Process Status
        uses: actions/github-script@v7
        with:
          script: |
            const status = context.payload.client_payload.status;
            const timestamp = new Date(context.payload.client_payload.timestamp);

            console.log(`Status: ${status}`);
            console.log(`Timestamp: ${timestamp.toISOString()}`);

            const statusJson = {
              schemaVersion: 1,
              label: "last sync",
              message: `${status} ${timestamp.toISOString()}`,
              color: status === "synced" ? "green" : "red"
            };

            const fileName = 'status.json';

            const fs = require('fs');
            fs.writeFileSync(fileName, JSON.stringify(statusJson, null, 2));

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: status-artifact
          path: status.json

      - name: Check out status branch
        id: checkout_status_branch
        if: always() # Ensures this runs even if previous steps fail
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check out the status branch
          git fetch origin status
          git checkout status

          last_commit_message=$(git log -1 --pretty=%B)
          if [[ "$last_commit_message" != "${STATUS_COMMIT_MESSAGE}" ]]; then
            echo "Last commit message is not '${STATUS_COMMIT_MESSAGE}'. Skipping commit."
          else
            cp status.json sync-status.json
            git add sync-status.json
            git commit --amend -m "${STATUS_COMMIT_MESSAGE}"
            git push --force origin status
          fi
