name: Update sync status

on:
  repository_dispatch:
    types: [sync_status_update]

jobs:
  process-status:
    runs-on: ubuntu-latest
    steps:
      - name: Process Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.AIRSYNC_GIST_TOKEN }}
          script: |
            const status = context.payload.client_payload.status;
            const timestamp = new Date(context.payload.client_payload.timestamp);
            const timeText = timestamp.toISOString().split('.')[0]+"Z";

            const payload = {
              schemaVersion: 1,
              label: "last sync",
              message: `${status} ${timeText}`,
              color: status === "synced" ? "green" : "red"
            };
            console.log(`Payload: ${payload}`);

            const gistId = '26502e2a8b93eedb9cd15229cdee4c59';
            const fileName = 'airtable-sync.status.json';

            const updatedContent = {
              files: {
                [fileName]: {
                  content: JSON.stringify(payload, null, 2)
                }
              }
            };

            try {
              const response = await github.gists.update({
                gist_id: gistId,
                ...updatedContent
              });
              console.log(`Updated Gist: ${response.data.html_url}, files: ${response.data.files}`);
            } catch (error) {
              console.error("Error updating Gist:", error.response ? error.response.data : error.message);
            }
