name: Update sync status

on:
  repository_dispatch:
    types: [sync_status_update]

jobs:
  process-status:
    runs-on: ubuntu-latest
    steps:
      - name: Process Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.AIRSYNC_GIST_TOKEN }}
          script: |
            const status = context.payload.client_payload.status;
            const timestamp = new Date(context.payload.client_payload.timestamp);
            const timeText = timestamp.toISOString().split('.')[0]+"Z";

            const payload = JSON.stringify({
              schemaVersion: 1,
              label: "last sync",
              message: `${status} ${timeText}`,
              color: status === "synced" ? "green" : "red"
            }, null, 2);
            console.log(`Payload: ${payload}`);

            const gistId = '26502e2a8b93eedb9cd15229cdee4c59';
            const fileName = 'airtable-sync.status.json';

            const updatedContent = {
              files: {
                [fileName]: {
                  content: payload
                }
              }
            };

            console.log('GitHub API context:', github);
            const response = await github.rest.gists.update({
              gist_id: gistId,
              ...updatedContent
            });
            console.log(`Updated Gist: ${response.data.html_url}`);
            console.log(`  files: ${JSON.stringify(response.data.files, null, 2)}`);
